// ======================================================= Requeste de Usuário
###
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
    "name": "Pedro",
    "email": "pedros@hotmail.com",
    "password": "123456",
    "role": "admin"
}

###
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "teste@hotmail.com",
    "password": "123456"
}

// ======================================================= Requeste de Banda

###
POST http://localhost:3003/band/create
Content-Type: application/json

{
    "name": "Claudinha",
    "musicGenre": "samba",
    "responsible": "Cleito"
}

###
GET http://localhost:3003/band/return
Content-Type: application/json

{
    "name": "Claudinha"
}


// ======================================================= Requeste de Show

###
POST http://localhost:3003/show/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjRjYzU1MjE2LWVjMDEtNDM3MC05NzI5LWZmMjA0NmFkMWEyMSJ9LCJpYXQiOjE2NjkyMjQxMjYsImV4cCI6MTY2OTIyNzcyNn0.qnQMqVuvXBjMGPmaQg56zltj_HRov1omjcQGQZIXXOc
Content-Type: application/json

{
    "weekDay" : "SEXTA", 
    "startTime" : 10, 
    "endTime" : 22, 
    "bandId" : 2
}

###
GET http://localhost:3003/show/get/SEXTA
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6eyJpZCI6IjRjYzU1MjE2LWVjMDEtNDM3MC05NzI5LWZmMjA0NmFkMWEyMSJ9LCJpYXQiOjE2NjkyMjQxMjYsImV4cCI6MTY2OTIyNzcyNn0.qnQMqVuvXBjMGPmaQg56zltj_HRov1omjcQGQZIXXOc


