
###
POST http://localhost:3003/user/signup 
Content-Type: application/json

{
    "name": "Max",
    "email": "max@hotmail.com",
    "password": "654321",
    "role": "normal"
}

###
POST http://localhost:3003/band/create
Content-Type: application/json

{
    "name": "Coldplay",
    "musicGenre": "samba",
    "responsible": "joao"
}
