// Requests de User
###
POST http://localhost:3003/user/signup 
Content-Type: application/json

{

    "name": "Teste",
    "email": "teste@hotmail.com",
    "password": "123456",
    "role": "normal"

    "name": "Bento",
    "email": "bento@hotmail.com",
    "password": "123456",
    "role": "ADMIN"

}

###
POST http://localhost:3003/user/login 
Content-Type: application/json

{
    "email": "teste@hotmail.com",
    "password": "123456"
}
###
POST http://localhost:3003/band/create
Content-Type: application/json

{
    "name": "Claudinha",
    "musicGenre": "samba",
    "responsible": "Teste"
}


// Requests de Show

###
POST http://localhost:3003/show/create
Content-Type: application/json

{
    "weekDay" : "SEXTA", 
    "startTime" : 10, 
    "endTime" : 22, 
    "bandId" : 2
}

###
GET http://localhost:3003/show/get/SEGUNDA

